# Required
base_url = 'http://example.com'
title = "my blog"
theme = "casper" # to disable theming, specify "none".

# Optional, will be empty by default
subtitle = ""
description = '''
enter some description here
'''
copyright = "Copyright 2018 <your_name>"

# Optional, will be this value by default
lang    = "en-us"
source  = "src"     # directory to find source files
output  = "output"  # directory to output processed files
content = "content" # files in this directory will be copied directly to ./${output}/
themes  = "themes"  # directory to find themes

# Optional, disabled by default
tag     = "tag"     # tag archives will be generated to
                    # ./${output}/${tag}/${tag-name}.html
archive = "archive" # monthly archives will be generated to
                    # ./${output}/${archive}/${yyyy}-${mm}.html
# cache   = ".cache"  # directory to store caches for skipping unchanged documents
                      # (not implemented yet)

## Markdown config (optional) 
markdown = "common"   # set this "advanced" to enable popular extensions
# markdown_extra_rules = "extra_rules"
                      # put your custom rule definitions here (not implemented yet)

