// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("1.0.3297.3611")>]
[<assembly: AssemblyFileVersionAttribute("1.0.3297.3611")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "1.0.3297.3611"
    let [<Literal>] AssemblyFileVersion = "1.0.3297.3611"
