// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("1.0.3297.19702")>]
[<assembly: AssemblyFileVersionAttribute("1.0.3297.19702")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "1.0.3297.19702"
    let [<Literal>] AssemblyFileVersion = "1.0.3297.19702"
